# Generated by Django 4.2.6 on 2023-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='number_of_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sum_of_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
