# Generated by Django 4.2.6 on 2023-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_ID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='number_of_games_played',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sum_of_points',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_ID',
            field=models.IntegerField(default=-1),
        ),
    ]
