# Generated by Django 4.2.6 on 2023-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=64)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('picture_URL_1', models.URLField(max_length=256)),
                ('picture_URL_2', models.URLField(max_length=256)),
                ('picture_URL_3', models.URLField(max_length=256)),
                ('picture_URL_4', models.URLField(max_length=256)),
                ('hint_1', models.CharField(max_length=512)),
                ('hint_2', models.CharField(max_length=512)),
                ('hint_3', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'UserData',
            },
        ),
    ]
