# Generated by Django 4.2.6 on 2023-10-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_ID',
        ),
    ]
